language: python
sudo: false  # Speed up build, allegedly.
python:
  - "3.6"
install:
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
# command to run tests
script:
  - pytest --cov=tregex tregex/
# Push the results back to codecov
after_success:
  - coveralls