language: python
dist: xenial
sudo: false
python:
- '3.6'
- '3.7'
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
script:
- pytest --cov=tregex tregex
after_success:
- coveralls
deploy:
  provider: pypi
  user: tobiasli
  password:
    secure: tQNoYpHrgvGyTaY8AxcGmeyO9ICD4yQywR65QR3JUlfipPHewWcRclzCT3wk1ZQ1jzNFGCe7KZv9nv0iZRjxuyPD9z/yv3kXwUlZMkSDFIhK9VaW1hNuyCQqqSCVUFItFQg4OA8Ji+ZdsTpy9kZ2R70tMQ/3KYiB/YOPXJAfJ4z4p5rET5U5YP6ryf1gHmqCTeZ0o86jSgEBBx1JGh8IyBHS/Zo6fQjaufmQJiBu/6kk1eaKfFy0beUv6FmBQHBoYiMVuQEKBIYCRdKlzONxo7jO9lhuBrgnbCKYOks3Ww6jI7jhAK8WWcKVLss5Zl7TOyt2RP3wvSc1aQspxXsfxzoRBu/7Ubyef7DIPcff4BEQ+lJoy1nRyFob7KA/vxGh7qj89X+fO3UeqcjAJPcWpGLnNwM6gOlYEatZKFZD5fG056ha/yDXCHlUEWSEFQLJzP1+4zptJw2SD9G2AoXIlGOK2ihM4XwPij9dY2rLak+r1HkjpLnTwJd5fKhc2XgaIM2K7uihxQ7cv4sQ3rfu8B9DViLyMAkvFeFgSUtirWuMde0dJ2drr6LTjvP6jV7nN6D9meuxDdouoxOY8jb3GOiee9SyqFZqRMYAtS1K9CHeOxeamqz1pxZIQFvaNv27owVwQJCQx6WHES11bH3jHVcwjfY/FDFez8VNGj1ddG0=
  on:
    branch: master
